contacts and footer
medvol/team-project-5 pull request #19
Opened 2022-05-16 22:37 UTC by TarasZagamula

2022-05-17 13:02 UTC, Siyavush-Moseyko requested changes

2022-05-17 13:02 UTC, Siyavush-Moseyko commented on src/sass/layout/_footer.scss
> +.contact-tel__spun {
заменить на span

2022-05-18 06:51 UTC, TarasZagamula commented on src/partials/contacts.html
> +        <h2 class="title contacts-title">Registration for a <spun class="contacts-spun">free</spun> phone <spun class="contacts-spun">consultation</spun> on the nuances of English UPE</h2>
поправил

2022-05-18 06:51 UTC, TarasZagamula commented on src/partials/contacts.html
> +        <p class="contacts-text">Leave a request for participation in a <spun class="contacts-spun">free lesson</spun>. A consultant will contact you and answer your questions</p>
поправил

2022-05-18 06:51 UTC, TarasZagamula commented on src/partials/footer.html
> +                    <spun class="contact-tel__spun">+38 (000) 000 00 00</spun>
поправил

2022-05-18 06:51 UTC, TarasZagamula commented on src/partials/footer.html
> +                <a href="/" class="link footer__insta-logo">
поправил

2022-05-18 06:51 UTC, TarasZagamula commented on src/sass/layout/_footer.scss
> +    background: var(--third-background-color);
поправил

2022-05-18 06:51 UTC, TarasZagamula commented on src/sass/layout/_footer.scss
> +    padding-top: 40px;
поправил

2022-05-18 06:52 UTC, TarasZagamula commented on src/sass/layout/_footer.scss
> +.contact-tel__spun {
поправил

2022-05-18 11:39 UTC, Siyavush-Moseyko approved these changes

2022-05-18 14:56 UTC, medvol approved these changes

2022-05-18 14:56 UTC, merged