markup and styles for benefits section
medvol/team-project-5 pull request #8
Opened 2022-05-13 14:12 UTC by Yuliia-O

Позиционирование секции убрала на время работы в коменты

2022-05-14 11:12 UTC, medvol requested changes

2022-05-14 11:12 UTC, medvol commented on src/sass/layout/_benefits.scss
> +    position: relative;
css лічильники

2022-05-14 11:12 UTC, medvol commented on src/sass/layout/_benefits.scss
> +        flex-basis: calc(100% / 4);
добавити батьківському елементу правий марджин -204

2022-05-14 12:53 UTC, Yuliia-O commented on src/partials/benefits.html
> +<section class="benefits section">
+

2022-05-14 12:53 UTC, Yuliia-O commented on src/sass/layout/_benefits.scss
> +        padding: 40px 92px;
є

2022-05-14 12:54 UTC, Yuliia-O commented on src/sass/layout/_benefits.scss
> +        min-width: 1648px;
є

2022-05-14 12:54 UTC, Yuliia-O commented on src/sass/layout/_benefits.scss
> +        padding: 60px 192px 60px 140px;
є

2022-05-14 12:54 UTC, Yuliia-O commented on src/sass/layout/_benefits.scss
> +    position: relative;
є

2022-05-14 12:56 UTC, Yuliia-O commented on src/sass/layout/_benefits.scss
> +        flex-basis: calc(100% / 4);
зробила через gap. 
тут є бекграунд колор на списку тому від'ємні марджини ломають візуал

2022-05-15 20:04 UTC, medvol approved these changes

2022-05-15 20:04 UTC, merged