Feature problems
medvol/team-project-5 pull request #9
Opened 2022-05-13 15:59 UTC by alexej4

2022-05-14 07:49 UTC, medvol requested changes

2022-05-14 07:49 UTC, medvol commented on src/partials/problems.html
> +    <div class="problem">
class container?

2022-05-14 07:49 UTC, medvol commented on src/partials/problems.html
> +                in English UPE, which<br>
br? а як ти на мобілці будеш цей заголовок робити? на мобілці інший перенос слів

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    background-image: linear-gradient(to bottom, rgba(17, 21, 24, 1), rgba(241, 242, 245, 0.4));
Фон секції виконати градієнтом (згори чорний, білий внизу).

background-image: linear-gradient(to bottom, rgba(0, 0, 0, 1), rgba(255, 255, 255, 0.4));

З прозорістю треба дивитись що на макеті виходить

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    height: 470px;
min-height

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    height: 470px;
min-height

2022-05-14 07:49 UTC, medvol commented on src/partials/problems.html
> +    <div class="problem">
тут має бути клас container

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    height: 545px;
min-height

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    height: 470px;
тут точно 470? а не 340?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    display: inline-block;
для чого inline-block?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-top: 80px;
ці відступи від секції мають приходити і тут 24px

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    font-style: normal;
забрати, це від body приходить

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    line-height: 130%;
в цілих числах вказувати

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    color: #FFFFFF;
через var вказувати

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    font-style: normal;
забрати

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    color: #FFFFFF;
var

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    font-style: normal;
забрати

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    color: #FFFFFF;
var

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    line-height: 130%;
цілі числа а не %

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    color: #FF6B09;
var

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-bottom: 350px;
для чого це тут

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-bottom: 200px;
?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-bottom: 132px;
?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-right: 15px;
?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    padding-left: 15px;
падінг 20 12 24 32

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +        @media screen and (min-width: $mobile) {
це винести в базові стилі

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            padding-top: 20px;
винести в базові стилі і однією властивісю padding записати

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            right: 15px;
left:0

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            top: 230px;
точно 230?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            top: 200px;
169px

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            left: 15px;
left:0  і це прийде з мобілки, не треба дублювати код

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            margin-left: auto;
не потрібно, в тебе блок по макету на всю ширину контейнера

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            margin-right: auto;
аналогічно

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            width: 670px;
для чого? в тебе блок стане на ширину контейнера

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            padding-top: 32px;
одніює властивістю падінг запиши

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            left: 15px;
left:0

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            width: 1648px;
для чого?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +            padding-top: 60px;
однією властивістю падінг запиши

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +        background-color: #FFFFFF;
не потрібно воно від боді прийде

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +        color: #111518;
var

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +        margin-top: 50px;
це що таке?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    width: calc(100%/3 - 30px);
точно 30px?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    width: calc(100%/2 - 30px);
точно 30px?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    margin-left: 30px;
?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    margin-top: 50px;
?

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +    font-style: normal;
від боді приходить

2022-05-14 07:49 UTC, medvol commented on src/sass/layout/_problems.scss
> +        position: absolute;
чому ти його позиціонуєш? він хіба не стане над блоком?

2022-05-16 09:18 UTC, medvol requested changes

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +        margin-bottom: 45px;
тут в тебе 16 px

і заверни цей клас в правило

@media screen and (max-width: 767px)

бо в тебе це є тільки в мобілці

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +        position: relative;
цього тут не треба

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +        counter-increment: number;
це перемісти до класу  &::before який нижче

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +            position: absolute;
це тут не потрібно. не треба позиціонувати його, в тебе він і без цього встане вище тексту бо це блочний елемент

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +            top: -20px;
не потрібно

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +            top: -30px;
не потрібно

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +            top: -40px;
не потрібно

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +        &::before {
добав сюди margin bottom 5 пікселів для мобілки, 4 пікселі для планшета і 8 пікселів для десктоп. Це для того щоб пвседоелемент відштовхнути від тексту знизу

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +        &::before {
добав display: block

2022-05-16 09:18 UTC, medvol commented on src/sass/layout/_problems.scss
> +            font-weight: 700;
не дублюй властивість counter-increment: number;

2022-05-16 18:57 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    height: 470px;
+

2022-05-16 18:58 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    height: 470px;
done

2022-05-16 18:58 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    height: 470px;
done

2022-05-16 18:58 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    width: calc(100%/2 - 30px);
виправив

2022-05-16 18:59 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    margin-left: 30px;
виправив

2022-05-16 18:59 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    margin-top: 50px;
виправив

2022-05-16 19:01 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +    font-style: normal;
не приходить! напевно із за absolute!?

2022-05-16 19:01 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        position: absolute;
виправив

2022-05-16 19:01 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        margin-bottom: 157px;
убрав

2022-05-16 19:01 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        padding-bottom: 129px;
убрав

2022-05-16 19:02 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        margin-bottom: 132px;
убрав

2022-05-16 19:02 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        color: #FFFFFF;
виправив

2022-05-16 19:02 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +            top: -30px;
виправив

2022-05-16 19:02 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +            top: -40px;
виправив

2022-05-16 19:03 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        &::before {
зробив

2022-05-16 19:03 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +        &::before {
додав

2022-05-16 19:03 UTC, alexej4 commented on src/sass/layout/_problems.scss
> +            font-weight: 700;
виправив

2022-05-16 20:03 UTC, merged